<a href="https://colab.research.google.com/github/supraja57/DSP/blob/master/Day19_work(15_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn#sklearn is scikit learn

In [0]:
#Importing the Dataset                        read_csv gives output in proper format as by default seperationis ,
data = pd.read_table("http://bit.ly/movieusers")#here it is seperated by pipe seperated structure
data.head(2)

1|24|M|technician|85711
0      2|53|F|other|94043
1     3|23|M|writer|32067

In [0]:
data = pd.read_table("http://bit.ly/movieusers",sep= "|")
data.head(2)                                                 #here data is also coming as heading

1  24  M technician  85711
0  2  53  F      other  94043
1  3  23  M     writer  32067

In [0]:
data = pd.read_table("http://bit.ly/movieusers",sep= "|",header=None)
data.head(2)  

0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043

In [0]:
#handling the missing values

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv")
df         #-99999 is not a proper data      NaN is a missing value     0 is not missing value

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [0]:
df.day.dtype#dtype returns datatype of column            it is showing as object datatype

dtype('O')

In [0]:
type(df.day[0]) #but it is date type format   so it should be chnaged to date type format as it may lead to changes in output

str

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv",parse_dates=['day'])
df          #parse_dates is to convert datatype to date

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02       -99999          7  Sunny
2 2017-01-03           28     -99999   Snow
3 2017-01-04       -99999          7      0
4 2017-01-05           32     -99999   Rain
5 2017-01-06           31          2  Sunny
6 2017-01-06           34          5      0

In [0]:
df.day.dtype

dtype('<M8[ns]')

In [0]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [0]:
df['temperature']

0       32
1   -99999
2       28
3   -99999
4       32
5       31
6       34
Name: temperature, dtype: int64

In [0]:
df['temperature'].value_counts()   #mode        #gives the count of each value which helps to know do we have proper values r not               i.e it returns the frequency of column values

-99999    2
 32       2
 31       1
 28       1
 34       1
Name: temperature, dtype: int64

In [0]:
df.duplicated()#checks the duplicate values of columns

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [0]:
df[df.duplicated()]##Checking for duplicate values

Empty DataFrame
Columns: [day, temperature, windspeed, event]
Index: []

In [0]:
df['temperature'].duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
6    False
Name: temperature, dtype: bool

In [0]:
df[df['temperature'].duplicated()]#Checking for duplicate specific temperature column

day  temperature  windspeed event
3  1/4/2017       -99999          7     0
4  1/5/2017           32     -99999  Rain

In [0]:
df[df['event'].duplicated()]

day  temperature  windspeed  event
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [0]:
df['event'].value_counts()

Rain     2
Sunny    2
0        2
Snow     1
Name: event, dtype: int64

In [0]:
#replacing extreme values with Nan
new_df = df.replace({'temperature':-99999,'windspeed':-99999,'event':'0'},np.nan)
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
Imputation:Imputation is a process of substituting the missing values

In [0]:
##fillna()  is a function which is used to fill the missing values

In [0]:
new_df.isnull()

day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False        False      False  False
6  False        False      False   True

In [0]:
new_df.isnull().sum()

day            0
temperature    2
windspeed      2
event          2
dtype: int64

In [0]:
df1 = new_df.fillna(0) #i.e fill missing values with 0 
df1 #shift_Tab 4 times for documentation to be appeared in the kernel

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          0.0        7.0  Sunny
2 2017-01-03         28.0        0.0   Snow
3 2017-01-04          0.0        7.0      0
4 2017-01-05         32.0        0.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0      0

In [0]:
df1 = new_df.fillna(0,inplace = True) 
df1 

In [0]:
f_data = new_df.fillna(method = 'ffill')  #ffill is for forward fill
f_data                              #fillna will work only if nan values are present

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         28.0        7.0   Snow
4 2017-01-05         32.0        7.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0  Sunny

In [0]:
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
#bfill --> backfill
b_data = new_df.fillna(method = 'bfill')
b_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         28.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         32.0        7.0   Rain
4 2017-01-05         32.0        2.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
new_df.mean()

temperature    31.4
windspeed       5.4
dtype: float64

In [0]:
mean_data = new_df.fillna(new_df.mean()) #filling the missing values with mean   is mean imputation
mean_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         31.4        7.0  Sunny
2 2017-01-03         28.0        5.4   Snow
3 2017-01-04         31.4        7.0    NaN
4 2017-01-05         32.0        5.4   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
#Median imputation

In [0]:
new_df.median()

temperature    32.0
windspeed       6.0
dtype: float64

In [0]:
median_data = new_df.fillna(new_df.median())
median_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        6.0   Snow
3 2017-01-04         32.0        7.0    NaN
4 2017-01-05         32.0        6.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [0]:
new_df['event']

0     Rain
1    Sunny
2     Snow
3      NaN
4     Rain
5    Sunny
6      NaN
Name: event, dtype: object

In [0]:
new_df.event.mode()##most repeated values have low indices

0     Rain
1    Sunny
dtype: object

In [0]:
new_df.event.mode().iloc[0]

'Rain'

In [0]:
new_df['event'] = new_df['event'].fillna(new_df.event.mode().iloc[0])
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0   Rain
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0   Rain

In [0]:
##question 12

In [0]:
import numpy as np
arr1 = np.array([[19,7,19,93],[94,18,4,22],[5,21,95,17],[20,92,20,6]])

In [0]:
arr1

array([[19,  7, 19, 93],
       [94, 18,  4, 22],
       [ 5, 21, 95, 17],
       [20, 92, 20,  6]])

In [0]:
s= 0#sum of middle square is 138
for i in range(4):
  for j in range(4):
    if i!=0 and i!=3 and j!=0 and j!=3:
      s += arr1[i,j]
s

138

In [0]:
#sum of column is 138
arr1.sum(axis=1)

array([138, 138, 138, 138])

In [0]:
arr1[0,0]+arr1[0,3]+arr1[3,0]+arr1[3,3]#sum of corner elements is 138

138

In [0]:
f=0#sum of forward diagonal
b=0#for backward
for i in range(4):
  for j in range(4):
    if i==j:
      f += arr1[i,j]
    if i+j==3:
      b += arr1[i,j]
print(f)
print(b)

138
138


In [0]:
print(arr1[0,0]+arr1[0,1]+arr1[1,0]+arr1[1,1])
s=0
for i in range(2):
  for j in range(2):
    s += arr1[i,j]
print(s)

138
138


In [0]:
#sum of rows is 138
arr1.sum(axis=0)

array([138, 138, 138, 138])

In [0]:
#forward diagonal sum
arr1.trace(axis1 = 1,axis2 = 0)

138

In [0]:
arr1.trace(axis1=0,axis2 =1)

138