# Numpy:

In [7]:
import numpy as np
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
type(arr1)

numpy.ndarray

In [9]:
#1 -dimensional array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [12]:
#2-dimen array
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# inserting elements into the array dynamically
a3 = np.array([],dtype="int32")

In [15]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [22]:
a3 = np.append(a3,[23,34,45,56,67])
a3

array([12, 23, 34, 45, 56, 67, 23, 34, 45, 56, 67])

# Slicing:

In [17]:
print(a3[3])

45


In [24]:
print(a1[1,1])

5


In [27]:
print(a1[2:,:])

[[7 8 9]]


# lterate through array:

In [28]:
for row in a1:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [30]:
for ele in a1.flat:
    print(ele,end="")

123456789

In [31]:
np.array(a1.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing with boolean array

In [32]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
result = (arr1 % 2 ==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [35]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Appending array

In [38]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20). reshape(3,3)
print(np.vstack((arr1,arr2)))#vertical stracking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [37]:
print(arr2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [39]:
print(np.hstack((arr1,arr2))) #horizontial stracking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [40]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


## Functions:
1. zeros()
2. ones()
3. full()
4. arange
5. reshape
6. ravel

In [48]:
z = np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
o = np.ones((3,3),dtype="int32")
o

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
f = np.full((2,2),"SUPRAJA")
print(f)

[['SUPRAJA' 'SUPRAJA']
 ['SUPRAJA' 'SUPRAJA']]


In [51]:
a = np.arange(1,13,2)#range(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [53]:
a = a.reshape(2,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [55]:
#ravel() -->flattens ypor array elements
print(np.array(a.flat))
print(a.ravel())

[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


# Functions:
1. min()
2. max()
3. sum()
4. squrt()
5. mean()
6. median()
7. std()

In [56]:
print(a.min())
print(a.max())

1
11


In [57]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [59]:
print(a.sum())# all
print(a.sum(axis=1))#row
print(a.sum(axis=0))#colume

36
[ 9 27]
[ 8 12 16]


In [60]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [62]:
np.mean(a)

6.0

In [63]:
np.median(a)

6.0

In [65]:
np.std(a)

3.415650255319866

In [72]:
arr1 =np.arange(1,10)
arr2= np.arange(11,20)
print(arr1+arr2)
print(arr1-arr2)
print(arr1%arr2)
print(arr1*arr2)
print(arr1/arr2)

[12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10]
[1 2 3 4 5 6 7 8 9]
[ 11  24  39  56  75  96 119 144 171]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]


In [77]:
arr1 =np.arange(1,10).reshape(3,3)
arr2 =np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [79]:

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arr.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# appiying user-defined function:

In [82]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [83]:
a = np.array(list1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [84]:
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [85]:
f = np.vectorize(lambda x : x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])