<a href="https://colab.research.google.com/github/supraja57/DSP/blob/master/Day21_work(17_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import sklearn

In [ ]:
price = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv")
price

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
Dummy variables using scikit learn library
-labelencoder
-one hot encoder

In [ ]:
LabelEncoder-->we are creting dummy variables
-class present in sklearn library
-creted an object for the class
-to apply the object to the dataset(town), we use fit_transform method
syntax: objectname.fit_transform(datasetName.columnName)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()#created an object

In [ ]:
price_data = data.copy()
price_data#copy of dataset

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
price_data.town = le.fit_transform(data.town)#as algorithms,it is madeup of equations
price_data#it may lead to errors due to complexity of numbers and tere is no relation betwwen each two

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
OneHotEncoder -->similar to pd.get_dummies
-import the OneHotEncoder class
-create an object for the class
-ColumnTranformer-->Insider this column transformer,we will pass this OneHotEncoder
-it has two mandatory arguments-->tansformns,remainder
-transformers argument:it accepts a list of tuple values

In [ ]:
#Importing libraries
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
#Inside the columntransformer,we habve to pass the OneHotEncoder
column_transformer = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [ ]:
##objectname.fit_transform(data)

In [ ]:
data = column_transformer.fit_transform(data)
data

array([[1.00e+00, 0.00e+00, 0.00e+00, 2.60e+03, 5.50e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.00e+03, 5.65e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.20e+03, 6.10e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.60e+03, 6.80e+05],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.00e+03, 7.25e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.60e+03, 5.85e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.80e+03, 6.15e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.30e+03, 6.50e+05],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.60e+03, 7.10e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.60e+03, 5.75e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 2.90e+03, 6.00e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.10e+03, 6.20e+05],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.60e+03, 6.95e+05]])

In [ ]:
X = pd.DataFrame(data)##creating a dataframe outof array
X#if passthrough is not given ,3 and 4 willnot print

0    1    2       3         4
0   1.0  0.0  0.0  2600.0  550000.0
1   1.0  0.0  0.0  3000.0  565000.0
2   1.0  0.0  0.0  3200.0  610000.0
3   1.0  0.0  0.0  3600.0  680000.0
4   1.0  0.0  0.0  4000.0  725000.0
5   0.0  0.0  1.0  2600.0  585000.0
6   0.0  0.0  1.0  2800.0  615000.0
7   0.0  0.0  1.0  3300.0  650000.0
8   0.0  0.0  1.0  3600.0  710000.0
9   0.0  1.0  0.0  2600.0  575000.0
10  0.0  1.0  0.0  2900.0  600000.0
11  0.0  1.0  0.0  3100.0  620000.0
12  0.0  1.0  0.0  3600.0  695000.0

In [ ]:
#Splitting the Dataset

In [ ]:
-->how well the model is working

In [ ]:
-seperate the input and output
-input and ouput seperately to the model

In [ ]:
price = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/homeprices.csv")

In [ ]:
X = price.iloc[:,0:2]#input should be in capital
X
#y=##output should be in small

town  area
0   monroe township  2600
1   monroe township  3000
2   monroe township  3200
3   monroe township  3600
4   monroe township  4000
5      west windsor  2600
6      west windsor  2800
7      west windsor  3300
8      west windsor  3600
9       robinsville  2600
10      robinsville  2900
11      robinsville  3100
12      robinsville  3600

In [ ]:
#preparing the output variables
y = price.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=659)#20% of data is given to testing data


In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(10, 2)
(3, 2)
(10,)
(3,)


In [ ]:
X_train

town  area
5      west windsor  2600
9       robinsville  2600
2   monroe township  3200
11      robinsville  3100
8      west windsor  3600
10      robinsville  2900
3   monroe township  3600
0   monroe township  2600
6      west windsor  2800
7      west windsor  3300

In [ ]:
#Feature Scaling:(Not mandatory for all the )

In [ ]:
sample = pd.DataFrame({'W.E':[2,4,5,6,7,8],'Age':[28,25,32,45,33,32],'Salary':[300000,400000,500000,600000,700000,800000],'Distance':[10,12,14,16,18,20],
                       'Expected Salary':[400000,500000,600000,700000,800000,900000]})
sample

W.E  Age  Salary  Distance  Expected Salary
0    2   28  300000        10           400000
1    4   25  400000        12           500000
2    5   32  500000        14           600000
3    6   45  600000        16           700000
4    7   33  700000        18           800000
5    8   32  800000        20           900000

In [ ]:
standard_data = sample.copy()
standard_data

0         1        2        3        4
0 -1.690309 -0.721348 -1.46385 -1.46385 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.87831 -0.87831
2 -0.169031 -0.080150 -0.29277 -0.29277 -0.29277
3  0.338062  2.003744  0.29277  0.29277  0.29277
4  0.845154  0.080150  0.87831  0.87831  0.87831
5  1.352247 -0.080150  1.46385  1.46385  1.46385

In [ ]:
-->Most of the machine learning algorithms,we use distance based formula
-->also,all the columns in our dataset,belong to differet units,exp->years,sal->currency
-->units and scales(magnitude)
-->Features scaling-->when applied,this units and scaling will be removed


In [ ]:
from sklearn.preprocessing import scale
scaled_data = scale(sample)
scaled_data

array([[-1.69030851, -0.72134777, -1.46385011, -1.46385011, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.87831007, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002, -0.29277002, -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  0.29277002,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007,  0.87831007,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011,  1.46385011,  1.46385011]])

In [ ]:
scaled_data = pd.DataFrame(scaled_data)
scaled_data


0         1        2        3        4
0 -1.690309 -0.721348 -1.46385 -1.46385 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.87831 -0.87831
2 -0.169031 -0.080150 -0.29277 -0.29277 -0.29277
3  0.338062  2.003744  0.29277  0.29277  0.29277
4  0.845154  0.080150  0.87831  0.87831  0.87831
5  1.352247 -0.080150  1.46385  1.46385  1.46385

In [ ]:
##using standardscaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()#creating an object 
sample = sc.fit_transform(sample)
sample

array([[-1.69030851, -0.72134777, -1.46385011, -1.46385011, -1.46385011],
       [-0.6761234 , -1.20224629, -0.87831007, -0.87831007, -0.87831007],
       [-0.16903085, -0.08014975, -0.29277002, -0.29277002, -0.29277002],
       [ 0.3380617 ,  2.00374382,  0.29277002,  0.29277002,  0.29277002],
       [ 0.84515425,  0.08014975,  0.87831007,  0.87831007,  0.87831007],
       [ 1.35224681, -0.08014975,  1.46385011,  1.46385011,  1.46385011]])

In [ ]:
sample = pd.DataFrame(sample)
sample

0         1        2        3        4
0 -1.690309 -0.721348 -1.46385 -1.46385 -1.46385
1 -0.676123 -1.202246 -0.87831 -0.87831 -0.87831
2 -0.169031 -0.080150 -0.29277 -0.29277 -0.29277
3  0.338062  2.003744  0.29277  0.29277  0.29277
4  0.845154  0.080150  0.87831  0.87831  0.87831
5  1.352247 -0.080150  1.46385  1.46385  1.46385

In [ ]:
##minmax scalar

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
ms.fit(standard_data)
standard_data=ms.transform(standard_data)
standard_data

In [ ]:
standard_data= pd.DataFrame(standard_data)
standard_data