## Class(day-34:2-7-20)
## Document link:- http://tiny.cc/02-07-2020

## Importing Libraries:

In [2]:
import pandas as pd
import numpy as np

## Reading the data:

In [3]:
data = pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/spam.csv",encoding='latin-1')
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
data.shape


(5572, 5)

In [5]:
# Drop the unnecessary columns
data.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1, inplace=True)
data.shape

(5572, 2)

## splitting the data:

In [6]:
# split the data
# 80% of the data will be in training data  20% of the data will be in testing
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.v2,data.v1,test_size = 0.2)

In [7]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4457,)
(4457,)
(1115,)
(1115,)


## initialising count vectorizer

In [8]:
# count vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# creating an object for countvectorizer
count_vect = CountVectorizer()

## To get the feature names:

In [9]:
# generate the word counts for the words in the documents
word_count_vector = count_vect.fit(x_train)

# to get the feature names
word_count_vector.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07123456789',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700469649',
 '0870062117

## Transforming the data:

In [10]:
doc_array = word_count_vector.transform(x_train)
doc_array

<4457x7789 sparse matrix of type '<class 'numpy.int64'>'
	with 58933 stored elements in Compressed Sparse Row format>

In [11]:
# converting to a array
doc_array = word_count_vector.transform(x_train).toarray()
doc_array

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Specifying column names

In [12]:
# converting the array into a dataframe
pd.DataFrame(doc_array)

0     1     2     3     4     5     6     7     8     9     ...  7779  \
0        0     0     0     0     0     0     0     0     0     0  ...     0   
1        0     0     0     0     0     0     0     0     0     0  ...     0   
2        0     0     0     0     0     0     0     0     0     0  ...     0   
3        0     0     0     0     0     0     0     0     0     0  ...     0   
4        0     0     0     0     0     0     0     0     0     0  ...     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
4452     0     0     0     0     0     0     0     0     0     0  ...     0   
4453     0     0     0     0     0     0     0     0     0     0  ...     0   
4454     0     0     0     0     0     0     0     0     0     0  ...     0   
4455     0     0     0     0     0     0     0     0     0     0  ...     0   
4456     0     0     0     0     0     0     0     0     0     0  ...     0   

      7780  7781  7782  7783  7784  7785  7786  7787  7788  
0        0     0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0     0  
2        0     0     0     0     0     0     0     0     0  
3        0     0     0     0     0     0     0     0     0  
4        0     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
4452     0     0     0     0     0     0     0     0     0  
4453     0     0     0     0     0     0     0     0     0  
4454     0     0     0     0     0     0     0     0     0  
4455     0     0     0     0     0     0     0     0     0  
4456     0     0     0     0     0     0     0     0     0  

[4457 rows x 7789 columns]

In [13]:
feature_matrix = pd.DataFrame(doc_array,columns= word_count_vector.get_feature_names())
feature_matrix

00  000  000pes  008704050406  01223585236  01223585334  0125698789  02  \
0      0    0       0             0            0            0           0   0   
1      0    0       0             0            0            0           0   0   
2      0    0       0             0            0            0           0   0   
3      0    0       0             0            0            0           0   0   
4      0    0       0             0            0            0           0   0   
...   ..  ...     ...           ...          ...          ...         ...  ..   
4452   0    0       0             0            0            0           0   0   
4453   0    0       0             0            0            0           0   0   
4454   0    0       0             0            0            0           0   0   
4455   0    0       0             0            0            0           0   0   
4456   0    0       0             0            0            0           0   0   

      0207  02072069400  ...  ìï  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  \
0        0            0  ...   0   0   0         0    0    0     0   0   
1        0            0  ...   0   0   0         0    0    0     0   0   
2        0            0  ...   0   0   0         0    0    0     0   0   
3        0            0  ...   0   0   0         0    0    0     0   0   
4        0            0  ...   0   0   0         0    0    0     0   0   
...    ...          ...  ...  ..  ..  ..       ...  ...  ...   ...  ..   
4452     0            0  ...   0   0   0         0    0    0     0   0   
4453     0            0  ...   0   0   0         0    0    0     0   0   
4454     0            0  ...   0   0   0         0    0    0     0   0   
4455     0            0  ...   0   0   0         0    0    0     0   0   
4456     0            0  ...   0   0   0         0    0    0     0   0   

      ûïharry  ûò  
0           0   0  
1           0   0  
2           0   0  
3           0   0  
4           0   0  
...       ...  ..  
4452        0   0  
4453        0   0  
4454        0   0  
4455        0   0  
4456        0   0  

[4457 rows x 7789 columns]

In [14]:
# pd.set_option('display.max_rows',None)

# Class(day-35:3-7-20)

In [15]:
# TFIDF Vectorizer
# Import TfIDF Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize and object for the TFIDF Vectorizer
tfidf = TfidfVectorizer()

In [16]:
# apply the tfidf to the data(x_train)
x_train_transformed = tfidf.fit_transform(x_train)
x_train_transformed

<4457x7789 sparse matrix of type '<class 'numpy.float64'>'
	with 58933 stored elements in Compressed Sparse Row format>

In [17]:

x_test_transformed = tfidf.transform(x_test)
x_test_transformed

<1115x7789 sparse matrix of type '<class 'numpy.float64'>'
	with 14043 stored elements in Compressed Sparse Row format>

In [18]:
# Feature Names
tfidf.get_feature_names()

['00',
 '000',
 '000pes',
 '008704050406',
 '01223585236',
 '01223585334',
 '0125698789',
 '02',
 '0207',
 '02072069400',
 '02073162414',
 '02085076972',
 '021',
 '03',
 '04',
 '0430',
 '05',
 '050703',
 '0578',
 '06',
 '07',
 '07008009200',
 '07046744435',
 '07090201529',
 '07090298926',
 '07123456789',
 '07732584351',
 '07734396839',
 '07742676969',
 '07753741225',
 '0776xxxxxxx',
 '07781482378',
 '07786200117',
 '077xxx',
 '07801543489',
 '07808',
 '07808247860',
 '07808726822',
 '07815296484',
 '07821230901',
 '078498',
 '07880867867',
 '07946746291',
 '0796xxxxxx',
 '07973788240',
 '07xxxxxxxxx',
 '08',
 '0800',
 '08000407165',
 '08000776320',
 '08000839402',
 '08000930705',
 '08000938767',
 '08001950382',
 '08002888812',
 '08002986030',
 '08002986906',
 '08002988890',
 '08006344447',
 '0808',
 '08081263000',
 '08081560665',
 '0825',
 '083',
 '0844',
 '08448350055',
 '08448714184',
 '0845',
 '08450542832',
 '08452810073',
 '08452810075over18',
 '0870',
 '08700469649',
 '0870062117

## Vocabulary Position:

In [19]:
# position of the words in the sparse matrix
tfidf.vocabulary_

{'lul': 4302,
 'im': 3660,
 'gettin': 3156,
 'some': 6322,
 'juicy': 3913,
 'gossip': 3234,
 'at': 1133,
 'the': 6850,
 'hospital': 3550,
 'two': 7126,
 'nurses': 4886,
 'are': 1067,
 'talking': 6732,
 'about': 770,
 'how': 3567,
 'fat': 2818,
 'they': 6873,
 'and': 979,
 'one': 4964,
 'thinks': 6884,
 'shes': 6113,
 'obese': 4904,
 'oyea': 5066,
 'hi': 3465,
 'happy': 3371,
 'birthday': 1383,
 'much': 4668,
 'trying': 7092,
 'to': 6967,
 'get': 3149,
 'going': 3206,
 'for': 2973,
 'bath': 1265,
 'will': 7547,
 'msg': 4650,
 'you': 7734,
 'next': 4791,
 'lt': 4293,
 'gt': 3297,
 'min': 4519,
 'hope': 3535,
 'had': 3327,
 'good': 3217,
 'day': 2203,
 'have': 3394,
 'better': 1350,
 'night': 4802,
 'thanks': 6836,
 'looking': 4243,
 'out': 5032,
 'me': 4445,
 'really': 5638,
 'appreciate': 1046,
 'prakesh': 5382,
 'is': 3796,
 'there': 6866,
 'know': 4005,
 'its': 3814,
 'so': 6308,
 'common': 1944,
 'hearin': 3417,
 'wat': 7422,
 'doing': 2425,
 'was': 7416,
 'ur': 7232,
 'let': 4127,
 

In [20]:
# Idf of the terms
tfidf.idf_

array([7.32301397, 6.22440168, 8.70930833, ..., 8.70930833, 8.70930833,
       7.45654536])

In [21]:

# Apply the naive Bayes Algorithm
# Import BernNB
from sklearn.naive_bayes import BernoulliNB
# creating an object for BerNB
model_BernNB = BernoulliNB()

In [22]:
# Applying the algorithm to the data
# objectName.fit(Input,Output)
model_BernNB.fit(x_train_transformed, y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [23]:
# prediction on test data
# SYNTAX: objectname.predict(InputValues)
y_test_pred = model_BernNB.predict(x_test_transformed)

In [24]:
# compare the actual values(y_test) with predicted values(y_test_pred)
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test,y_test_pred)

array([[962,   0],
       [ 30, 123]], dtype=int64)

In [25]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98       962
        spam       1.00      0.80      0.89       153

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115



## Testing for new message

In [26]:

# test a single message --> Spam or Ham
new_message = pd.Series('Last few days to collect the free entry passes with 40% discount')
#calculate tfidf values for the new message
new_message_transformed = tfidf.transform(new_message)

In [27]:
# predict the new message
model_BernNB.predict(new_message_transformed)

array(['ham'], dtype='<U4')