# NUMPY random package:

In [2]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

78
0.38440988155807887


In [4]:
#creating n-dimensional
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[45 65  3]
[[88 48 44  5]
 [22 44 56 14]
 [37 99 10 79]]
[[[18 93]
  [41 19]
  [32 54]
  [12 59]]

 [[40 37]
  [19 52]
  [ 6 44]
  [53  0]]

 [[34 78]
  [31 63]
  [85  0]
  [57 73]]]


In [5]:
#creatund n-dimensional
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.7658256145212774
[0.56219674 0.78123756 0.10948215]
[[0.80982673 0.95158239 0.13341384]
 [0.11812911 0.88753255 0.58725219]]


In [10]:
#single element will be seletected
a=(1,20)
random.choice(a)

20

In [11]:
#for generating an array
random.choice([1,2,3,4,5],size=(4,4))

array([[5, 1, 3, 5],
       [5, 5, 5, 1],
       [4, 5, 4, 2],
       [3, 3, 1, 1]])

# Pandas:

# Creating a Data Frame:
1. Create DataFrame with two dictionaries
2. We can also create simply by creating a dictionary and converting it directly to a DataFrame.
3. Create DataFrame with Series
4. DataFrame can also be created by using the CSV File

In [15]:
import pandas as pd
import numpy as nd
dict1 ={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2= {'a':5,'b':6,'c':7,'d':8,'f':9}
data ={"First":dict1,"Second":dict2}
df = pd.DataFrame(data)
df

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [17]:
import pandas as pd
import numpy as np
dict1 ={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2= {'a':5,'b':6,'c':7,'d':8,'e':9}
data ={"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [18]:
#series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,25.36,69.3])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e
5        6    67.78       f
6        7    78.89       g
7        8    89.90       h
8        9    25.36       i
9       10    69.30       j

# selecting the data from the dataframe
1. loc
2. iloc

In [19]:
df3["column2"]

0    12.23
1    23.34
2    34.45
3    45.56
4    56.67
5    67.78
6    78.89
7    89.90
8    25.36
9    69.30
Name: column2, dtype: float64

In [21]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    34.45       c
3    45.56       d
4    56.67       e
5    67.78       f
6    78.89       g
7    89.90       h
8    25.36       i
9    69.30       j

In [22]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [29]:
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    12.23
1        2    23.34
2        3    34.45
3        4    45.56
4        5    56.67
5        6    67.78

In [30]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [31]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

# Retrieving the information of dataframe

In [32]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 264.0+ bytes


In [33]:
df3.shape

(10, 3)

In [34]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [35]:
df3.index

RangeIndex(start=0, stop=10, step=1)

# Viewing data from dataframe
1. head()
2. tail()
3. samaple()

In [36]:
#first five rows
df3.head()

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e

In [37]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c

In [38]:
df3.tail(2)

column1  column2 column3
8        9    25.36       i
9       10    69.30       j

In [41]:
df3.sample()

column1  column2 column3
1        2    23.34       b

In [42]:
df3.sample(2)

column1  column2 column3
5        6    67.78       f
8        9    25.36       i

In [43]:
df3.describe()

column1   column2
count  10.00000  10.00000
mean    5.50000  50.34800
std     3.02765  26.17147
min     1.00000  12.23000
25%     3.25000  27.63250
50%     5.50000  51.11500
75%     7.75000  68.92000
max    10.00000  89.90000

In [44]:
#Remaining the column headers
df3 =df3.rename(columns={"column1":"first","column2":"second","column3":"third"})
df3

first  second third
0      1   12.23     a
1      2   23.34     b
2      3   34.45     c
3      4   45.56     d
4      5   56.67     e
5      6   67.78     f
6      7   78.89     g
7      8   89.90     h
8      9   25.36     i
9     10   69.30     j